using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

public enum COMBAT_USE {
    COMBAT_USE_NONE,
    COMBAT_USE_MELEE,
    COMBAT_USE_MISSILE,
    COMBAT_USE_AMMO,
    COMBAT_USE_SHIELD,
    COMBAT_USE_TWO_HANDED
}

public enum AMMO_TYPE {
    AMMO_NONE,
    AMMO_ARROW,
    AMMO_BOLT,
    AMMO_ATLATL,
    AMMO_ARROW_CRYSTAL,
    AMMO_BOLT_CRYSTAL,
    AMMO_ATLATL_CRYSTAL,
    AMMO_ARROW_CHORIZITE,
    AMMO_BOLT_CHORIZITE,
    AMMO_ATLATL_CHORIZITE
}

public enum ITEM_TYPE {
    TYPE_UNDEF = 0,
    //TYPE_SELF = 0, This is a duplicate of TYPE_UNDEF
    TYPE_MELEE_WEAPON = (1 << 0),
    TYPE_ARMOR = (1 << 1),
    TYPE_CLOTHING = (1 << 2),
    TYPE_VESTEMENTS = 6,
    TYPE_JEWELRY = (1 << 3),
    TYPE_CREATURE = (1 << 4),
    TYPE_FOOD = (1 << 5),
    TYPE_MONEY = (1 << 6),
    TYPE_MISC = (1 << 7),
    TYPE_MISSILE_WEAPON = (1 << 8),
    TYPE_WEAPON = 0x101,
    TYPE_CONTAINER = (1 << 9),
    TYPE_LOCKABLE_MAGIC_TARGET = 0x280,
    TYPE_USELESS = (1 << 10),
    TYPE_GEM = (1 << 11),
    TYPE_SPELL_COMPONENTS = (1 << 12),
    TYPE_WRITABLE = (1 << 13),
    TYPE_KEY = (1 << 14),
    TYPE_CASTER = (1 << 15),
    TYPE_WEAPON_OR_CASTER = 0x8101,
    TYPE_REDIRECTABLE_ITEM_ENCHANTMENT_TARGET = 0x8107,
    TYPE_PORTAL = (1 << 16),
    TYPE_LOCKABLE = (1 << 17),
    TYPE_PROMISSORY_NOTE = (1 << 18),
    TYPE_MANASTONE = (1 << 19),
    TYPE_ITEM_ENCHANTABLE_TARGET = 0x88B8F,
    TYPE_SERVICE = (1 << 20),
    TYPE_MAGIC_WIELDABLE = (1 << 21),
    TYPE_ITEM = 0x2DFBEF,
    TYPE_CRAFT_COOKING_BASE = (1 << 22),
    TYPE_VENDOR_GROCER = 0x446220,
    TYPE_CRAFT_ALCHEMY_BASE = (1 << 23),
    TYPE_CRAFT_FLETCHING_BASE = (1 << 24),
    // Skip 1
    TYPE_CRAFT_ALCHEMY_INTERMEDIATE = (1 << 26),
    TYPE_CRAFT_FLETCHING_INTERMEDIATE = (1 << 27),
    TYPE_LIFESTONE = (1 << 28),
    TYPE_PORTAL_MAGIC_TARGET = 0x10010000,
    TYPE_TINKERING_TOOL = (1 << 29),
    TYPE_TINKERING_MATERIAL = (1 << 30),
    TYPE_VENDOR_SHOPKEEP = 0x480467A7,
    TYPE_GAMEBOARD = (1 << 31),
}

public enum ITEM_USEABLE {
    USEABLE_UNDEF = 0,
    USEABLE_NO = (1 << 0),
    USEABLE_SELF = (1 << 1),
    USEABLE_WIELDED = (1 << 2),
    USEABLE_CONTAINED = (1 << 3),
    USEABLE_VIEWED = (1 << 4),
    USEABLE_REMOTE = (1 << 5),
    USEABLE_NEVER_WALK = (1 << 6),
    USEABLE_OBJSELF = (1 << 7),
    USEABLE_CONTAINED_VIEWED = 24,
    USEABLE_CONTAINED_VIEWED_REMOTE = 56,
    USEABLE_CONTAINED_VIEWED_REMOTE_NEVER_WALK = 120,
    USEABLE_VIEWED_REMOTE = 48,
    USEABLE_VIEWED_REMOTE_NEVER_WALK = 112,
    USEABLE_REMOTE_NEVER_WALK = 96,
    USEABLE_SOURCE_WIELDED_TARGET_WIELDED = 262148,
    USEABLE_SOURCE_WIELDED_TARGET_CONTAINED = 524292,
    USEABLE_SOURCE_WIELDED_TARGET_VIEWED = 1048580,
    USEABLE_SOURCE_WIELDED_TARGET_REMOTE = 2097156,
    USEABLE_SOURCE_WIELDED_TARGET_REMOTE_NEVER_WALK = 6291460,
    USEABLE_SOURCE_CONTAINED_TARGET_WIELDED = 262152,
    USEABLE_SOURCE_CONTAINED_TARGET_CONTAINED = 524296,
    USEABLE_SOURCE_CONTAINED_TARGET_OBJSELF_OR_CONTAINED = 8912904,
    USEABLE_SOURCE_CONTAINED_TARGET_SELF_OR_CONTAINED = 655368,
    USEABLE_SOURCE_CONTAINED_TARGET_VIEWED = 1048584,
    USEABLE_SOURCE_CONTAINED_TARGET_REMOTE = 2097160,
    USEABLE_SOURCE_CONTAINED_TARGET_REMOTE_NEVER_WALK = 6291464,
    USEABLE_SOURCE_CONTAINED_TARGET_REMOTE_OR_SELF = 2228232,
    USEABLE_SOURCE_VIEWED_TARGET_WIELDED = 262160,
    USEABLE_SOURCE_VIEWED_TARGET_CONTAINED = 524304,
    USEABLE_SOURCE_VIEWED_TARGET_VIEWED = 1048592,
    USEABLE_SOURCE_VIEWED_TARGET_REMOTE = 2097168,
    USEABLE_SOURCE_REMOTE_TARGET_WIELDED = 262176,
    USEABLE_SOURCE_REMOTE_TARGET_CONTAINED = 524320,
    USEABLE_SOURCE_REMOTE_TARGET_VIEWED = 1048608,
    USEABLE_SOURCE_REMOTE_TARGET_REMOTE = 2097184,
    USEABLE_SOURCE_REMOTE_TARGET_REMOTE_NEVER_WALK = 6291488,
    USEABLE_SOURCE_MASK = 65535,
    USEABLE_TARGET_MASK = -65536,
}

public enum ImbuedEffectType {
    Undef_ImbuedEffectType = 0,
    CriticalStrike_ImbuedEffectType = (1 << 0),
    CripplingBlow_ImbuedEffectType = (1 << 1),
    ArmorRending_ImbuedEffectType = (1 << 2),
    SlashRending_ImbuedEffectType = (1 << 3),
    PierceRending_ImbuedEffectType = (1 << 4),
    BludgeonRending_ImbuedEffectType = (1 << 5),
    AcidRending_ImbuedEffectType = (1 << 6),
    ColdRending_ImbuedEffectType = (1 << 7),
    ElectricRending_ImbuedEffectType = (1 << 8),
    FireRending_ImbuedEffectType = (1 << 9),
    MeleeDefense_ImbuedEffectType = (1 << 10),
    MissileDefense_ImbuedEffectType = (1 << 11),
    MagicDefense_ImbuedEffectType = (1 << 12),
    Spellbook_ImbuedEffectType = (1 << 13),
    NetherRending_ImbuedEffectType = (1 << 14),
    IgnoreSomeMagicProjectileDamage_ImbuedEffectType = (1 << 29),
    AlwaysCritical_ImbuedEffectType = (1 << 30),
    IgnoreAllArmor_ImbuedEffectType = (1 << 31)
}

public enum WeaponType {
    Undef_WeaponType,
    Unarmed_WeaponType,
    Sword_WeaponType,
    Axe_WeaponType,
    Mace_WeaponType,
    Spear_WeaponType,
    Dagger_WeaponType,
    Staff_WeaponType,
    Bow_WeaponType,
    Crossbow_WeaponType,
    Thrown_WeaponType,
    TwoHanded_WeaponType,
    Magic_WeaponType
}

public enum HookAppraisal_BF {
    BF_INSCRIBABLE = (1 << 0),
    BF_HEALER = (1 << 1),
    BF_FOOD = (1 << 2),
    BF_LOCKPICK = (1 << 2)
}

public enum AttunedStatusEnum {
    Normal_AttunedStatus,
    Attuned_AttunedStatus,
    Sticky_AttunedStatus
}

public enum BondedStatusEnum {
    Destroy_BondedStatus = -2,
    Slippery_BondedStatus = -1,
    Normal_BondedStatus = 0,
    Bonded_BondedStatus = 1,
    Sticky_BondedStatus = 2
}

public enum EnchantmentTypeEnum {
    Undef_EnchantmentType                  = 0,
    Attribute_EnchantmentType              = (1 << 0),
    SecondAtt_EnchantmentType              = (1 << 1),
    Int_EnchantmentType                    = (1 << 2),
    Float_EnchantmentType                  = (1 << 3),
    Skill_EnchantmentType                  = (1 << 4),
    BodyDamageValue_EnchantmentType        = (1 << 5),
    BodyDamageVariance_EnchantmentType     = (1 << 6),
    BodyArmorValue_EnchantmentType         = (1 << 7), // Natural Armor
    // NOTE: Skip 4
    SingleStat_EnchantmentType             = (1 << 12),
    MultipleStat_EnchantmentType           = (1 << 13),
    Multiplicative_EnchantmentType         = (1 << 14),
    Additive_EnchantmentType               = (1 << 15),
    AttackSkills_EnchantmentType           = (1 << 16),
    DefenseSkills_EnchantmentType          = (1 << 17),
    // NOTE: Skip 3
    Multiplicative_Degrade_EnchantmentType = (1 << 20),
    Additive_Degrade_EnchantmentType       = (1 << 21),
    // NOTE: Skip 1
    Vitae_EnchantmentType                  = (1 << 23),
    Cooldown_EnchantmentType               = (1 << 24),
    Beneficial_EnchantmentType             = (1 << 25),
    StatTypes_EnchantmentType              = 255
}

public enum EquipmentSet {
    Invalid = 0,
    Test = 1,
    Test2 = 2,
    Unknown3 = 3,
    CarraidasBenediction = 4,
    NobleRelic = 5,
    AncientRelic = 6,
    AlduressaRelic = 7,
    Ninja = 8,
    EmpyreanRings = 9,
    ArmMindHeart = 10,
    ArmorPerfectLight = 11,
    ArmorPerfectLight2 = 12,
    Soldiers = 13,
    Adepts = 14,
    Archers = 15,
    Defenders = 16,
    Tinkers = 17,
    Crafters = 18,
    Hearty = 19,
    Dexterous = 20,
    Wise = 21,
    Swift = 22,
    Hardened = 23,
    Reinforced = 24,
    Interlocking = 25,
    Flameproof = 26,
    Acidproof = 27,
    Coldproof = 28,
    Lightningproof = 29,
    SocietyArmor = 30,
    ColosseumClothing = 31,
    GraveyardClothing = 32,
    OlthoiClothing = 33,
    NoobieArmor = 34,
    AetheriaDefense = 35,
    AetheriaDestruction = 36,
    AetheriaFury = 37,
    AetheriaGrowth = 38,
    AetheriaVigor = 39,
    RareDamageResistance = 40,
    RareDamageBoost = 41,
    OlthoiArmorDRed = 42,
    OlthoiArmorCRat = 43,
    OlthoiArmorCRed = 44,
    OlthoiArmorDRat = 45,
    AlduressaRelicUpgrade = 46,
    AncientRelicUpgrade = 47,
    NobleRelicUpgrade = 48,
    CloakAlchemy = 49,
    CloakArcaneLore = 50,
    CloakArmorTinkering = 51,
    CloakAssessPerson = 52,
    CloakAxe = 53,
    CloakBow = 54,
    CloakCooking = 55,
    CloakCreatureEnchantment = 56,
    CloakCrossbow = 57,
    CloakDagger = 58,
    CloakDeception = 59,
    CloakFletching = 60,
    CloakHealing = 61,
    CloakItemEnchantment = 62,
    CloakItemTinkering = 63,
    CloakLeadership = 64,
    CloakLifeMagic = 65,
    CloakLoyalty = 66,
    CloakMace = 67,
    CloakMagicDefense = 68,
    CloakMagicItemTinkering = 69,
    CloakManaConversion = 70,
    CloakMeleeDefense = 71,
    CloakMissileDefense = 72,
    CloakSalvaging = 73,
    CloakSpear = 74,
    CloakStaff = 75,
    CloakSword = 76,
    CloakThrownWeapon = 77,
    CloakTwoHandedCombat = 78,
    CloakUnarmedCombat = 79,
    CloakVoidMagic = 80,
    CloakWarMagic = 81,
    CloakWeaponTinkering = 82,
    CloakAssessCreature = 83,
    CloakDirtyFighting = 84,
    CloakDualWield = 85,
    CloakRecklessness = 86,
    CloakShield = 87,
    CloakSneakAttack = 88,
    // Shou-Jen Shozoku Set
    Ninja_New = 89,
    CloakSummoning = 90,
    ShroudedSoul = 91,
    DarkenedMind = 92,
    CloudedSpirit = 93,
    MinorStingingShroudedSoul = 94,
    MinorSparkingShroudedSoul = 95,
    MinorSmolderingShroudedSoul = 96,
    MinorShiveringShroudedSoul = 97,
    MinorStingingDarkenedMind = 98,
    MinorSparkingDarkenedMind = 99,
    MinorSmolderingDarkenedMind = 100,
    MinorShiveringDarkenedMind = 101,
    MinorStingingCloudedSpirit = 102,
    MinorSparkingCloudedSpirit = 103,
    MinorSmolderingCloudedSpirit = 104,
    MinorShiveringCloudedSpirit = 105,
    MajorStingingShroudedSoul = 106,
    MajorSparkingShroudedSoul = 107,
    MajorSmolderingShroudedSoul = 108,
    MajorShiveringShroudedSoul = 109,
    MajorStingingDarkenedMind = 110,
    MajorSparkingDarkenedMind = 111,
    MajorSmolderingDarkenedMind = 112,
    MajorShiveringDarkenedMind = 113,
    MajorStingingCloudedSpirit = 114,
    MajorSparkingCloudedSpirit = 115,
    MajorSmolderingCloudedSpirit = 116,
    MajorShiveringCloudedSpirit = 117,
    BlackfireStingingShroudedSoul = 118,
    BlackfireSparkingShroudedSoul = 119,
    BlackfireSmolderingShroudedSoul = 120,
    BlackfireShiveringShroudedSoul = 121,
    BlackfireStingingDarkenedMind = 122,
    BlackfireSparkingDarkenedMind = 123,
    BlackfireSmolderingDarkenedMind = 124,
    BlackfireShiveringDarkenedMind = 125,
    BlackfireStingingCloudedSpirit = 126,
    BlackfireSparkingCloudedSpirit = 127,
    BlackfireSmolderingCloudedSpirit = 128,
    BlackfireShiveringCloudedSpirit = 129,
    ShimmeringShadowsSet = 130,
    BrownSocietyLocket = 131,
    YellowSocietyLocket = 132,
    RedSocietyBand = 133,
    GreenSocietyBand = 134,
    PurpleSocietyBand = 135,
    BlueSocietyBand = 136,
    GauntletGarb = 137,
    ParagonMissile = 138,
    ParagonCaster = 139,
    ParagonMelee = 140,
}

public enum CoverageMask : uint
{
    UnderwearUpperLegs = 0x00000002,
    UnderwearLowerLegs = 0x00000004,
    UnderwearChest     = 0x00000008,
    UnderwearAbdomen   = 0x00000010,
    UnderwearUpperArms = 0x00000020,
    UnderwearLowerArms = 0x00000040,
    OuterwearUpperLegs = 0x00000100,
    OuterwearLowerLegs = 0x00000200,
    OuterwearChest     = 0x00000400,
    OuterwearAbdomen   = 0x00000800,
    OuterwearUpperArms = 0x00001000,
    OuterwearLowerArms = 0x00002000,
    Head               = 0x00004000,
    Hands              = 0x00008000,
    Feet               = 0x00010000,
}

// This enum is not found in the client.
public enum ContainerProperties
{
    None,
    Container,
    Foci
}

public enum PALETTE_TEMPLATE
{
    UNDEF_PALETTE_TEMPLATE,
    AQUABLUE_PALETTE_TEMPLATE,
    BLUE_PALETTE_TEMPLATE,
    BLUEPURPLE_PALETTE_TEMPLATE,
    BROWN_PALETTE_TEMPLATE,
    DARKBLUE_PALETTE_TEMPLATE,
    DEEPBROWN_PALETTE_TEMPLATE,
    DEEPGREEN_PALETTE_TEMPLATE,
    GREEN_PALETTE_TEMPLATE,
    GREY_PALETTE_TEMPLATE,
    LIGHTBLUE_PALETTE_TEMPLATE,
    MAROON_PALETTE_TEMPLATE,
    NAVY_PALETTE_TEMPLATE,
    PURPLE_PALETTE_TEMPLATE,
    RED_PALETTE_TEMPLATE,
    REDPURPLE_PALETTE_TEMPLATE,
    ROSE_PALETTE_TEMPLATE,
    YELLOW_PALETTE_TEMPLATE,
    YELLOWBROWN_PALETTE_TEMPLATE,
    COPPER_PALETTE_TEMPLATE,
    SILVER_PALETTE_TEMPLATE,
    GOLD_PALETTE_TEMPLATE,
    AQUA_PALETTE_TEMPLATE,
    DARKAQUAMETAL_PALETTE_TEMPLATE,
    DARKBLUEMETAL_PALETTE_TEMPLATE,
    DARKCOPPERMETAL_PALETTE_TEMPLATE,
    DARKGOLDMETAL_PALETTE_TEMPLATE,
    DARKGREENMETAL_PALETTE_TEMPLATE,
    DARKPURPLEMETAL_PALETTE_TEMPLATE,
    DARKREDMETAL_PALETTE_TEMPLATE,
    DARKSILVERMETAL_PALETTE_TEMPLATE,
    LIGHTAQUAMETAL_PALETTE_TEMPLATE,
    LIGHTBLUEMETAL_PALETTE_TEMPLATE,
    LIGHTCOPPERMETAL_PALETTE_TEMPLATE,
    LIGHTGOLDMETAL_PALETTE_TEMPLATE,
    LIGHTGREENMETAL_PALETTE_TEMPLATE,
    LIGHTPURPLEMETAL_PALETTE_TEMPLATE,
    LIGHTREDMETAL_PALETTE_TEMPLATE,
    LIGHTSILVERMETAL_PALETTE_TEMPLATE,
    BLACK_PALETTE_TEMPLATE,
    BRONZE_PALETTE_TEMPLATE,
    SANDYYELLOW_PALETTE_TEMPLATE,
    DARKBROWN_PALETTE_TEMPLATE,
    LIGHTBROWN_PALETTE_TEMPLATE,
    TANRED_PALETTE_TEMPLATE,
    PALEGREEN_PALETTE_TEMPLATE,
    TAN_PALETTE_TEMPLATE,
    PASTYYELLOW_PALETTE_TEMPLATE,
    SNOWYWHITE_PALETTE_TEMPLATE,
    RUDDYYELLOW_PALETTE_TEMPLATE,
    RUDDIERYELLOW_PALETTE_TEMPLATE,
    MIDGREY_PALETTE_TEMPLATE,
    DARKGREY_PALETTE_TEMPLATE,
    BLUEDULLSILVER_PALETTE_TEMPLATE,
    YELLOWPALESILVER_PALETTE_TEMPLATE,
    BROWNBLUEDARK_PALETTE_TEMPLATE,
    BROWNBLUEMED_PALETTE_TEMPLATE,
    GREENSILVER_PALETTE_TEMPLATE,
    BROWNGREEN_PALETTE_TEMPLATE,
    YELLOWGREEN_PALETTE_TEMPLATE,
    PALEPURPLE_PALETTE_TEMPLATE,
    WHITE_PALETTE_TEMPLATE,
    REDBROWN_PALETTE_TEMPLATE,
    GREENBROWN_PALETTE_TEMPLATE,
    ORANGEBROWN_PALETTE_TEMPLATE,
    PALEGREENBROWN_PALETTE_TEMPLATE,
    PALEORANGE_PALETTE_TEMPLATE,
    GREENSLIME_PALETTE_TEMPLATE,
    BLUESLIME_PALETTE_TEMPLATE,
    YELLOWSLIME_PALETTE_TEMPLATE,
    PURPLESLIME_PALETTE_TEMPLATE,
    DULLRED_PALETTE_TEMPLATE,
    GREYWHITE_PALETTE_TEMPLATE,
    MEDIUMGREY_PALETTE_TEMPLATE,
    DULLGREEN_PALETTE_TEMPLATE,
    OLIVEGREEN_PALETTE_TEMPLATE,
    ORANGE_PALETTE_TEMPLATE,
    BLUEGREEN_PALETTE_TEMPLATE,
    OLIVE_PALETTE_TEMPLATE,
    LEAD_PALETTE_TEMPLATE,
    IRON_PALETTE_TEMPLATE,
    LITEGREEN_PALETTE_TEMPLATE,
    PINKPURPLE_PALETTE_TEMPLATE,
    AMBER_PALETTE_TEMPLATE,
    DYEDARKGREEN_PALETTE_TEMPLATE,
    DYEDARKRED_PALETTE_TEMPLATE,
    DYEDARKYELLOW_PALETTE_TEMPLATE,
    DYEBOTCHED_PALETTE_TEMPLATE,
    DYEWINTERBLUE_PALETTE_TEMPLATE,
    DYEWINTERGREEN_PALETTE_TEMPLATE,
    DYEWINTERSILVER_PALETTE_TEMPLATE,
    DYESPRINGBLUE_PALETTE_TEMPLATE,
    DYESPRINGPURPLE_PALETTE_TEMPLATE,
    DYESPRINGBLACK_PALETTE_TEMPLATE
}

public enum WieldRequirement
{
    Invalid_WieldRequirement,
    WIELD_REQUIRES_SKILL_WieldRequirement,
    WIELD_REQUIRES_RAW_SKILL_WieldRequirement,
    WIELD_REQUIRES_ATTRIB_WieldRequirement,
    WIELD_REQUIRES_RAW_ATTRIB_WieldRequirement,
    WIELD_REQUIRES_SECONDARY_ATTRIB_WieldRequirement,
    WIELD_REQUIRES_RAW_SECONDARY_ATTRIB_WieldRequirement,
    WIELD_REQUIRES_LEVEL_WieldRequirement,
    WIELD_REQUIRES_TRAINING_WieldRequirement,
    WIELD_REQUIRES_INTSTAT_WieldRequirement,
    WIELD_REQUIRES_BOOLSTAT_WieldRequirement,
    WIELD_REQUIRES_CREATURE_TYPE_WieldRequirement,
    WIELD_REQUIRES_HERITAGE_TYPE_WieldRequirement
}

public enum ItemXpStyle
{
    Undef,
    Fixed,
    ScalesWithLevel,
    // This appears to be another "scales with level type" that appears in the client but was never used
    Unknown
}